#version 430

layout(local_size_x = 32, local_size_y = 32) in;

layout(binding = 0, rgba8) uniform image2D resultImage;

layout(push_constant) uniform params
{
  float time;
  float xMouse;
} pushConstant;



int maxRayMarchIter = 250;
float maxRayMarchDist = 100.0f;

struct Surface {
    vec3 col;
    float sd;
};

// Rotation matrix around the X axis.
mat3 rotateX(float theta) {
    float c = cos(theta);
    float s = sin(theta);
    return mat3(
        vec3(1, 0, 0),
        vec3(0, c, -s),
        vec3(0, s, c)
    );
}

// Rotation matrix around the Y axis.
mat3 rotateY(float theta) {
    float c = cos(theta);
    float s = sin(theta);
    return mat3(
        vec3(c, 0, s),
        vec3(0, 1, 0),
        vec3(-s, 0, c)
    );
}

// Rotation matrix around the Z axis.
mat3 rotateZ(float theta) {
    float c = cos(theta);
    float s = sin(theta);
    return mat3(
        vec3(c, -s, 0),
        vec3(s, c, 0),
        vec3(0, 0, 1)
    );
}

// Identity matrix.
mat3 identity() {
    return mat3(
        vec3(1, 0, 0),
        vec3(0, 1, 0),
        vec3(0, 0, 1)
    );
}


Surface sdSphere(vec3 p, vec3 offset, float r, vec3 col) {
    p = (p - offset);
    return Surface(col, length(p) - r);
}
Surface sdPlane(vec3 p, float offset, vec3 col) {
    return Surface(col, (p.y - offset));
}

Surface sdTorus( vec3 p, vec2 t, vec3 offset, vec3 col, mat3 transform)
{
  p -= offset;
  p *= transform;
  Surface s;
  s.col = col;
  vec2 q = vec2(length(p.xz)-t.x,p.y);
  s.sd = length(q) - t.y;
  return s;
}

Surface sdLink( vec3 p, float le, float r1, float r2, vec3 offset, vec3 col, mat3 transform)
{
  p -= offset;
  p *= transform;
  Surface s;
  s.col = col;
  vec3 q = vec3( p.x, max(abs(p.y)-le,0.0), p.z );
  
  s.sd = length(vec2(length(q.xy)-r1,q.z)) - r2;
  return s;
}

Surface sdCylinder(vec3 p, float h, float r, vec3 offset, vec3 col, mat3 transform)
{
    p -= offset;
    p *= transform;
    vec2 d = abs(vec2(length(p.xz),p.y)) - vec2(r,h);
    Surface surface;
    surface.sd = min(max(d.x,d.y),0.0) + length(max(d,0.0));
    surface.col = col;
    
    return surface;
}

Surface sdVerticalCapsule( vec3 p, float h, float r, vec3 offset, vec3 col, mat3 transform, float scalingParam)
{
  p -= offset;
  p *= transform;
  p.y -= clamp( p.y, 0.0, h );
  Surface s;
  s.col = col;
  s.sd = length( p ) - r - scalingParam * (1.0 + sin(3.0 * pushConstant.time));
  return s;
}

Surface minWithSurface(Surface first, Surface second) {
    if(first.sd < second.sd) return first;
    return second;
}

Surface sdScene(vec3 p) {
    mat3 headRotation = rotateZ(pushConstant.time) * rotateX(pushConstant.time);
    Surface head = sdSphere(p, vec3(0.0, 6.0,0.0), 1.5, vec3(1.0,0.0,0.0));
    Surface capsule = sdVerticalCapsule(p, 3.0, 0.9, vec3(0.0, 1.5,0.0), vec3(1.0,0.8,0.6), identity(), 0.07);
    Surface rightHand = sdVerticalCapsule(p, 2.0, 0.5, vec3(1.0, 3.5,0.0), vec3(1.0,0.8,0.6), rotateZ(2.9) * rotateX(0.5 * sin(3.0 * pushConstant.time)), 0.0);
    Surface leftHand = sdVerticalCapsule(p, 2.0, 0.5, vec3(-1.0, 3.5,0.0), vec3(1.0,0.8,0.6), rotateZ(sin(5.0 * pushConstant.time) * 0.2 - 0.6), 0.0);
    vec3 floorColor = vec3(1. + 0.7*mod(floor(p.x) + floor(p.z + 3.0 * pushConstant.time), 2.0));
    Surface plane = sdPlane(p, -1.9, floorColor);
    Surface rightLeg = sdVerticalCapsule(p, 2.5, 0.4, vec3(0.5, 0.9,0.0), vec3(1.0,0.8,0.6), rotateX(3.14 + sin(3.0 * pushConstant.time) * 0.5), 0.0);
    Surface leftLeg = sdVerticalCapsule(p, 2.5, 0.4, vec3(-0.5, 0.9,0.0), vec3(1.0,0.8,0.6), rotateX(3.14 - sin(3.0 * pushConstant.time) * 0.5), 0.0);
    Surface res = capsule;
    res = minWithSurface(res, head);
    res = minWithSurface(res, plane);
    res = minWithSurface(res, rightHand);
    res = minWithSurface(res, leftHand);
    res = minWithSurface(res, leftLeg);
    res = minWithSurface(res, rightLeg);
    
    return res;
    
}

vec3 calcNormal(vec3 p) {
  vec2 e = vec2(1.0, -1.0) * 0.0005;
  float r = 1.;
  return normalize(
    e.xyy * sdScene(p + e.xyy).sd +
    e.yyx * sdScene(p + e.yyx).sd +
    e.yxy * sdScene(p + e.yxy).sd +
    e.xxx * sdScene(p + e.xxx).sd);
}

Surface trace(vec3 ro, vec3 rd, float epsilon) {
    float totalDist = 0.0;
    Surface closestObj;
    for(int i = 0; i < maxRayMarchIter; ++i) {
        vec3 p = ro + rd * totalDist;
        closestObj = sdScene(p);
        if(closestObj.sd < epsilon) break;
        totalDist += 0.7 * closestObj.sd;
        if(totalDist > maxRayMarchDist) break;
    }
    closestObj.sd = totalDist;
    return closestObj;
}

void main()
{
    vec2 iResolution = vec2(1280,720);
    ivec2 fragCoord = ivec2(gl_GlobalInvocationID.xy);
    vec3 col = vec3(0.4,0.6,0.8);
    vec3 iMouse = vec3(pushConstant.xMouse, 0.0, 0.0);
    vec3 mouse = vec3(iMouse.xy/iResolution.xy - 0.5,iMouse.z-.5);
    mouse *= 2.0 * 3.14;
    vec3 cameraPos = vec3(15.0 * cos(mouse.x), 1.0, 15.0 * sin(mouse.x));
    vec3 cameraForward = normalize(vec3(0,1.0,0) - cameraPos);
    vec3 cameraUp = vec3(0.0,1.0,0.0);
    vec3 cameraRight = normalize(cross(cameraUp,cameraForward));
    vec3 lightPos = vec3(0,3.0,6.0);
    vec3 lightCol = vec3(1.0,1.0, 1.0);
    vec2 uv = (vec2(fragCoord.x, iResolution.y - fragCoord.y)/iResolution.xy - vec2(0.5));
    uv.x *= iResolution.x/iResolution.y;
    vec3 ro = cameraPos;
    float fov = 1.0;
    vec3 rd = normalize(uv.x * cameraRight + uv.y * cameraUp + fov * cameraForward);
    Surface s = trace(ro,rd, 0.001);
    if(s.sd < maxRayMarchDist) {
        vec3 p = ro + rd * s.sd;
        vec3 norm = calcNormal(p);
        vec3 lightDir = normalize(lightPos - p);
        vec3 camDir = normalize(cameraPos - p);
        float dif1 = clamp(dot(lightDir, norm), 0.2, 1.0);
        float dif2 = clamp(dot(normalize(lightDir + camDir), norm),0.0, 1.0);
        dif2 = pow(dif2, 120.0);
        col = lightCol * dif2 * 0.4 + s.col * dif1 * 0.6;
    }
    vec4 fragColor = vec4(col, 1.0);
    if (fragCoord.x < 1280 && fragCoord.y < 720)
      imageStore(resultImage, fragCoord, vec4(col, 1));
}